name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    name: Backend Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-redis@v1
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
        working-directory: backend
      - name: Unit Test
        working-directory: backend
        run: npm run test
      - name: E2E Test
        working-directory: backend
        run: npm run test:e2e